site_name: FancyGlow

theme:

  name: material

  font:
    text: "JetBrains Mono"

  site_url: https://fancyglow.strixmc.com

  extra_css:
    - stylesheets/extra.css

  palette:

    - scheme: slate
      primary: custom
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    - scheme: default
      primary: custom
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  
  logo: assets/logo.png

  favicon: assets/logo.png

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
    - header.autohide
    - content.tabs.link
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_url: https://github.com/Imhhitt/FancyGlow

repo_name: FancyGlow Source

extra:
  generator: true
  social:
    - icon: simple/spigotmc
      link: https://www.spigotmc.org/resources/116326/
    - icon: simple/modrinth
      link: https://modrinth.com/plugin/fancy-glow
    - icon: simple/builtbybit
      link: https://builtbybit.com/resources/43517/
    - icon: simple/discord
      link: https://discord.smartshub.dev/
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2025 FancyGlow Contributors

nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Utility: 'utility.md'
  - FAQ: 'faq.md'
  - API: 'API.md'